### ISSUE TITLE
Can not find v_a_l_instances.txt

### ISSUE THREAD

**Issue by zhixuanli** [lightas/CVPR2020_MANet#1]
At the end of the training, a not found error occurred.

```
****************************************************************************************************
updating ref frame and label
updating ref frame and label finished!
round:1 start
step:100800,now_lr:2.594665548347261e-06 ,loss:0.8945(0.2332)
step:100850,now_lr:2.0057841089456063e-06 ,loss:0.4172(0.2333)
step:100900,now_lr:1.396671174899606e-06 ,loss:0.3744(0.2334)
step:100950,now_lr:7.551236845208468e-07 ,loss:0.5247(0.2335)
step:101000,now_lr:2.193839914256819e-08 ,loss:0.4890(0.2336)
Traceback (most recent call last):
  File "train_stage2.py", line 437, in <module>
    manager.train()
  File "train_stage2.py", line 182, in train
    optimizer.step()
  File "/home/lzx/.conda/envs/amodal/lib/python3.7/site-packages/torch/optim/sgd.py", line 106, in step
    p.data.add_(-group['lr'], d_p)
RuntimeError: value cannot be converted to type float without overflow: (2.08647e-08,-6.77934e-09)
Testing
Traceback (most recent call last):
  File "test.py", line 366, in <module>
    main()
  File "test.py", line 41, in main
    seq_dict = json.load(open(_seq_list_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/lzx/Interactive_Segmentation/dataset/DAVIS2017/ImageSets/2017/v_a_l_instances.txt'
```

I have downloaded the DAVIS 2017 dataset from the link you provide: https://data.vision.ee.ethz.ch/csergi/share/davis/DAVIS-2017-trainval-480p.zip

Can you provide the `v_a_l_instances.txt`? Thank you!

**Comment by lightas** [comment]
Hi, this link contains the missing file.
https://drive.google.com/file/d/1aLPaQ_5lyAi3Lk3d2fOc_xewSrfcrQlc/view?usp=sharing

**Comment by zhixuanli** [comment]
Thank you so much!
